name: scripts

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8]
        framework: [tensorflow, pytorch]
    steps:
      - if: matrix.os == 'macos-latest'
        name: Install MacOS prerequisites
        run: brew install cairo pango gdk-pixbuf libffi
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - if: matrix.framework == 'tensorflow'
        name: Cache python modules (TF)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
      - if: matrix.framework == 'pytorch'
        name: Cache python modules (PT)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}
      - if: matrix.framework == 'tensorflow'
        name: Install package (TF)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
      - if: matrix.framework == 'pytorch'
        name: Install package (PT)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[torch] --upgrade

      - name: Run analysis script
        run: |
          wget https://github.com/mindee/doctr/releases/download/v0.1.0/sample.pdf
          python scripts/analyze.py sample.pdf --noblock

  test-evaluate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8]
        framework: [tensorflow, pytorch]
    steps:
      - if: matrix.os == 'macos-latest'
        name: Install MacOS prerequisites
        run: brew install cairo pango gdk-pixbuf libffi
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - if: matrix.framework == 'tensorflow'
        name: Cache python modules (TF)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
      - if: matrix.framework == 'pytorch'
        name: Cache python modules (PT)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}
      - if: matrix.framework == 'tensorflow'
        name: Install package (TF)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
      - if: matrix.framework == 'pytorch'
        name: Install package (PT)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[torch] --upgrade
      - name: Run evaluation script
        run: python scripts/evaluate.py db_resnet50 crnn_vgg16_bn --samples 10

  test-collectenv:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Run environment collection script
        run: python scripts/collect_env.py
